packages:
- name: "alpine"
  release: "ThinXR"
  version: "0.1.0"
  sources:
    - name: alpine
      file: examples/alpine/alpine.tar.gz
  config-dir:
    - name: alpine-configs
      dir: examples/alpine/config
  data-dir:
    - name: alpine-data
      dir: examples/alpine/data

- name: "alpine"
  release: "eXR"
  version: "0.1.0"
  sources:
    - name: alpine
      file: examples/alpine/alpine.tar.gz
  config-dir:
    - name: alpine-configs
      dir: examples/alpine/config
  data-dir:
    - name: alpine-data
      dir: examples/alpine/data
  copy_hostname: true
  copy_ems_cert: true
